# Generated by Django 5.2.3 on 2025-06-19 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="이력서 제목")),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("고졸", "고등학교 졸업"),
                            ("초대졸", "전문대 졸업"),
                            ("대졸", "대학교 졸업 (학사)"),
                            ("석사", "대학원 졸업 (석사)"),
                            ("박사", "대학원 졸업 (박사)"),
                        ],
                        max_length=10,
                        verbose_name="최종 학력",
                    ),
                ),
                (
                    "university",
                    models.CharField(blank=True, max_length=100, verbose_name="학교명"),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=100, verbose_name="전공"),
                ),
                (
                    "gpa",
                    models.CharField(blank=True, max_length=10, verbose_name="학점"),
                ),
                (
                    "experience_years",
                    models.IntegerField(blank=True, null=True, verbose_name="경력(년)"),
                ),
                ("job", models.CharField(max_length=255, verbose_name="희망 직무")),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="희망 근무지"),
                ),
                ("skills", models.TextField(blank=True, verbose_name="보유 기술")),
                (
                    "experience",
                    models.TextField(blank=True, verbose_name="경험/활동/교육"),
                ),
                (
                    "certifications",
                    models.TextField(blank=True, verbose_name="수상/자격증/어학"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
