# Generated by Django 5.2.2 on 2025-06-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.AddField(
            model_name='resume',
            name='education_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='학적상태'),
        ),
        migrations.AddField(
            model_name='resume',
            name='gpa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='학점'),
        ),
        migrations.AddField(
            model_name='resume',
            name='graduation_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='졸업상태'),
        ),
        migrations.AddField(
            model_name='resume',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='전공'),
        ),
        migrations.AddField(
            model_name='resume',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='대학명'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job',
            field=models.TextField(blank=True, null=True, verbose_name='희망 직무'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='희망 근무지'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='보유 기술'),
        ),
    ]
